export type MuscleGroup = 'back' | 'chest' | 'arms' | 'legs' | 'shoulders' | 'core'
export type Difficulty = 'beginner' | 'intermediate' | 'advanced'

export type Exercise = {
  id: string
  name: string
  muscleGroup: MuscleGroup
  sets: number
  reps: number
  repsLabel?: string
  description: string
  difficulty: Difficulty
  color: string
}

export const EXERCISES: Exercise[] = [
  // ─── BACK (8) ───────────────────────────────────────────────
  {
    id: 'back-1',
    name: 'Lat Pulldown',
    muscleGroup: 'back',
    sets: 3,
    reps: 12,
    difficulty: 'beginner',
    color: '#4ECDC4',
    description: 'Grip the bar slightly wider than shoulders. Pull down to your upper chest squeezing the lats. Control the return to full extension.',
  },
  {
    id: 'back-2',
    name: 'Seated Cable Row',
    muscleGroup: 'back',
    sets: 3,
    reps: 12,
    difficulty: 'beginner',
    color: '#4ECDC4',
    description: 'Sit tall with feet on the platform. Pull the handle to your lower abdomen driving elbows back. Hold 1 second then return slowly.',
  },
  {
    id: 'back-3',
    name: 'Dumbbell Row',
    muscleGroup: 'back',
    sets: 3,
    reps: 10,
    difficulty: 'beginner',
    color: '#4ECDC4',
    description: 'Brace one knee and hand on a bench. Row the dumbbell to your hip keeping the elbow close to your side. Squeeze at the top.',
  },
  {
    id: 'back-4',
    name: 'Pull-Up',
    muscleGroup: 'back',
    sets: 3,
    reps: 8,
    difficulty: 'intermediate',
    color: '#4ECDC4',
    description: 'Start in a dead hang with an overhand grip. Pull until your chin clears the bar, then lower with control. No kipping.',
  },
  {
    id: 'back-5',
    name: 'Barbell Row',
    muscleGroup: 'back',
    sets: 4,
    reps: 8,
    difficulty: 'intermediate',
    color: '#4ECDC4',
    description: 'Hinge at 45° with bar close to your shins. Pull to your lower chest flaring elbows slightly. Keep your core braced throughout.',
  },
  {
    id: 'back-6',
    name: 'T-Bar Row',
    muscleGroup: 'back',
    sets: 3,
    reps: 10,
    difficulty: 'intermediate',
    color: '#4ECDC4',
    description: 'Straddle the bar and hinge at the hips. Pull the plates to your sternum keeping your back flat and core engaged.',
  },
  {
    id: 'back-7',
    name: 'Deadlift',
    muscleGroup: 'back',
    sets: 4,
    reps: 5,
    difficulty: 'advanced',
    color: '#4ECDC4',
    description: 'Bar over mid-foot with a neutral grip. Push the floor away keeping the bar in contact with your legs. Lock out your hips at the top.',
  },
  {
    id: 'back-8',
    name: 'Rack Pull',
    muscleGroup: 'back',
    sets: 4,
    reps: 6,
    difficulty: 'advanced',
    color: '#4ECDC4',
    description: 'Set the bar at knee height. Brace hard and drive your hips forward to stand tall. Maximises upper back and trap engagement.',
  },

  // ─── CHEST (8) ──────────────────────────────────────────────
  {
    id: 'chest-1',
    name: 'Push-Up',
    muscleGroup: 'chest',
    sets: 3,
    reps: 15,
    difficulty: 'beginner',
    color: '#FF6B6B',
    description: 'Hands shoulder-width apart with your body in a straight line. Lower your chest to an inch from the floor, then press back up explosively.',
  },
  {
    id: 'chest-2',
    name: 'Dumbbell Chest Press',
    muscleGroup: 'chest',
    sets: 3,
    reps: 12,
    difficulty: 'beginner',
    color: '#FF6B6B',
    description: 'Lie flat with dumbbells at chest level. Press up arcing slightly at the top, then lower under control to get a full stretch.',
  },
  {
    id: 'chest-3',
    name: 'Cable Fly',
    muscleGroup: 'chest',
    sets: 3,
    reps: 15,
    difficulty: 'beginner',
    color: '#FF6B6B',
    description: 'Set cables at shoulder height. With a slight bend in elbows bring your hands together in a wide arc. Squeeze your pecs at the centre.',
  },
  {
    id: 'chest-4',
    name: 'Incline Dumbbell Press',
    muscleGroup: 'chest',
    sets: 3,
    reps: 12,
    difficulty: 'intermediate',
    color: '#FF6B6B',
    description: 'Bench at 30–45°. Press from just above shoulder level focusing on upper chest contraction as the dumbbells come together at the top.',
  },
  {
    id: 'chest-5',
    name: 'Bench Press',
    muscleGroup: 'chest',
    sets: 4,
    reps: 8,
    difficulty: 'intermediate',
    color: '#FF6B6B',
    description: 'Grip just outside shoulder-width. Lower the bar to your lower chest, touch lightly, and drive the bar back up keeping your arch natural.',
  },
  {
    id: 'chest-6',
    name: 'Dips',
    muscleGroup: 'chest',
    sets: 3,
    reps: 10,
    difficulty: 'intermediate',
    color: '#FF6B6B',
    description: 'Lean slightly forward to target the chest. Lower until elbows reach 90°, then press back up. Avoid shrugging your shoulders.',
  },
  {
    id: 'chest-7',
    name: 'Incline Barbell Press',
    muscleGroup: 'chest',
    sets: 4,
    reps: 8,
    difficulty: 'advanced',
    color: '#FF6B6B',
    description: 'Set incline to 30°. Unrack with straight arms and lower the bar to your upper chest. Press with power while maintaining full tightness.',
  },
  {
    id: 'chest-8',
    name: 'Cable Crossover',
    muscleGroup: 'chest',
    sets: 3,
    reps: 15,
    difficulty: 'intermediate',
    color: '#FF6B6B',
    description: 'Stand between two high cables. Sweep hands down and together with bent elbows. Maximises stretch at the bottom and contraction at the top.',
  },

  // ─── ARMS (8) ───────────────────────────────────────────────
  {
    id: 'arms-1',
    name: 'Dumbbell Curl',
    muscleGroup: 'arms',
    sets: 3,
    reps: 12,
    difficulty: 'beginner',
    color: '#A78BFA',
    description: 'Stand with dumbbells at your sides. Curl both up keeping elbows pinned to your torso and supinating at the top. Lower fully for a full stretch.',
  },
  {
    id: 'arms-2',
    name: 'Hammer Curl',
    muscleGroup: 'arms',
    sets: 3,
    reps: 12,
    difficulty: 'beginner',
    color: '#A78BFA',
    description: 'Neutral grip with thumbs pointing up. Curl with the same controlled motion as a standard curl. Targets brachialis and brachioradialis.',
  },
  {
    id: 'arms-3',
    name: 'Tricep Pushdown',
    muscleGroup: 'arms',
    sets: 3,
    reps: 15,
    difficulty: 'beginner',
    color: '#A78BFA',
    description: 'Use a rope or straight bar on a high cable. Keep elbows locked at your sides, extend fully downward and squeeze the triceps hard at the bottom.',
  },
  {
    id: 'arms-4',
    name: 'Skull Crusher',
    muscleGroup: 'arms',
    sets: 3,
    reps: 12,
    difficulty: 'intermediate',
    color: '#A78BFA',
    description: 'Lie on bench with an EZ-bar overhead. Lower the bar toward your forehead by bending only at the elbows. Press back up explosively.',
  },
  {
    id: 'arms-5',
    name: 'Barbell Curl',
    muscleGroup: 'arms',
    sets: 3,
    reps: 10,
    difficulty: 'intermediate',
    color: '#A78BFA',
    description: 'Shoulder-width underhand grip. Curl from full extension to full contraction at the top. Avoid swinging the torso for momentum.',
  },
  {
    id: 'arms-6',
    name: 'Close-Grip Bench Press',
    muscleGroup: 'arms',
    sets: 4,
    reps: 8,
    difficulty: 'intermediate',
    color: '#A78BFA',
    description: 'Grip inside shoulder-width on the bar. Press while keeping elbows close to your body throughout. Prioritises triceps over chest.',
  },
  {
    id: 'arms-7',
    name: 'Concentration Curl',
    muscleGroup: 'arms',
    sets: 3,
    reps: 12,
    difficulty: 'beginner',
    color: '#A78BFA',
    description: 'Seated with your elbow resting on your inner knee. Curl the dumbbell to shoulder height with full supination. Best isolation for peak contraction.',
  },
  {
    id: 'arms-8',
    name: 'Overhead Tricep Extension',
    muscleGroup: 'arms',
    sets: 3,
    reps: 12,
    difficulty: 'intermediate',
    color: '#A78BFA',
    description: 'Hold a dumbbell overhead with both hands. Lower behind your head with elbows pointing straight up, then extend back to the start position.',
  },

  // ─── LEGS (8) ───────────────────────────────────────────────
  {
    id: 'legs-1',
    name: 'Bodyweight Squat',
    muscleGroup: 'legs',
    sets: 3,
    reps: 15,
    difficulty: 'beginner',
    color: '#FCD34D',
    description: 'Feet shoulder-width apart with toes slightly out. Sit back and down until thighs are parallel to the floor. Drive through your heels to stand.',
  },
  {
    id: 'legs-2',
    name: 'Leg Press',
    muscleGroup: 'legs',
    sets: 3,
    reps: 12,
    difficulty: 'beginner',
    color: '#FCD34D',
    description: 'Place feet hip-width on the platform. Lower until knees reach 90°, then press back without fully locking out. Maintain control throughout.',
  },
  {
    id: 'legs-3',
    name: 'Walking Lunge',
    muscleGroup: 'legs',
    sets: 3,
    reps: 10,
    difficulty: 'beginner',
    color: '#FCD34D',
    description: 'Step forward and lower your rear knee to just above the floor. Push off your front foot to step through. Alternate legs for each rep.',
  },
  {
    id: 'legs-4',
    name: 'Goblet Squat',
    muscleGroup: 'legs',
    sets: 3,
    reps: 12,
    difficulty: 'beginner',
    color: '#FCD34D',
    description: 'Hold a dumbbell at chest height. Squat deep with elbows tracking inside your knees. Great for building squat mechanics and depth.',
  },
  {
    id: 'legs-5',
    name: 'Romanian Deadlift',
    muscleGroup: 'legs',
    sets: 3,
    reps: 10,
    difficulty: 'intermediate',
    color: '#FCD34D',
    description: 'Hold the bar at your hips and hinge backward keeping the bar close to your legs. Feel the hamstring stretch at the bottom, then drive hips forward.',
  },
  {
    id: 'legs-6',
    name: 'Barbell Squat',
    muscleGroup: 'legs',
    sets: 4,
    reps: 8,
    difficulty: 'intermediate',
    color: '#FCD34D',
    description: 'Bar on upper traps or rear delts. Brace hard, unrack, and squat to parallel or below. Drive your knees out actively on the way back up.',
  },
  {
    id: 'legs-7',
    name: 'Leg Curl',
    muscleGroup: 'legs',
    sets: 3,
    reps: 12,
    difficulty: 'beginner',
    color: '#FCD34D',
    description: 'Lie prone on the machine with pads above your heels. Curl your heels toward your glutes, pause briefly at the top, then lower slowly.',
  },
  {
    id: 'legs-8',
    name: 'Bulgarian Split Squat',
    muscleGroup: 'legs',
    sets: 3,
    reps: 10,
    difficulty: 'advanced',
    color: '#FCD34D',
    description: 'Rear foot elevated on a bench, front foot forward. Lower your back knee toward the floor and press through your front heel to return.',
  },

  // ─── SHOULDERS (8) ──────────────────────────────────────────
  {
    id: 'shoulders-1',
    name: 'Lateral Raise',
    muscleGroup: 'shoulders',
    sets: 3,
    reps: 15,
    difficulty: 'beginner',
    color: '#34D399',
    description: 'Slight bend in elbows, raise dumbbells to shoulder height. Lead with your elbows and keep your pinky slightly higher than your thumb. Lower slowly.',
  },
  {
    id: 'shoulders-2',
    name: 'Front Raise',
    muscleGroup: 'shoulders',
    sets: 3,
    reps: 12,
    difficulty: 'beginner',
    color: '#34D399',
    description: 'Arms straight, raise one dumbbell forward to shoulder height. Alternate sides. Keep your core braced and avoid swinging.',
  },
  {
    id: 'shoulders-3',
    name: 'Arnold Press',
    muscleGroup: 'shoulders',
    sets: 3,
    reps: 12,
    difficulty: 'intermediate',
    color: '#34D399',
    description: 'Start with palms facing you at chin level. Rotate as you press so palms face forward at the top. Reverse the rotation on the way down.',
  },
  {
    id: 'shoulders-4',
    name: 'Dumbbell Overhead Press',
    muscleGroup: 'shoulders',
    sets: 3,
    reps: 10,
    difficulty: 'intermediate',
    color: '#34D399',
    description: 'Dumbbells at ear level with elbows at 90°. Press straight overhead until arms are nearly locked out. Lower with control to the start.',
  },
  {
    id: 'shoulders-5',
    name: 'Face Pull',
    muscleGroup: 'shoulders',
    sets: 3,
    reps: 15,
    difficulty: 'beginner',
    color: '#34D399',
    description: 'Rope at face height on a cable. Pull toward your face with elbows flaring out wide. Excellent for rear delt and rotator cuff health.',
  },
  {
    id: 'shoulders-6',
    name: 'Upright Row',
    muscleGroup: 'shoulders',
    sets: 3,
    reps: 12,
    difficulty: 'intermediate',
    color: '#34D399',
    description: 'Narrow grip on a barbell. Pull the bar straight up to chin level with elbows flaring out. Lower with full control back to start.',
  },
  {
    id: 'shoulders-7',
    name: 'Military Press',
    muscleGroup: 'shoulders',
    sets: 4,
    reps: 6,
    difficulty: 'advanced',
    color: '#34D399',
    description: 'Bar at clavicle height with grip just outside shoulders. Press the bar overhead in a vertical line. Brace your core hard throughout.',
  },
  {
    id: 'shoulders-8',
    name: 'Cable Lateral Raise',
    muscleGroup: 'shoulders',
    sets: 3,
    reps: 15,
    difficulty: 'beginner',
    color: '#34D399',
    description: 'Low pulley at your side with the cable crossing your body. Raise your arm to shoulder height. Maintains constant tension on the lateral delt.',
  },

  // ─── CORE (8) ───────────────────────────────────────────────
  {
    id: 'core-1',
    name: 'Plank',
    muscleGroup: 'core',
    sets: 3,
    reps: 30,
    repsLabel: '30s',
    difficulty: 'beginner',
    color: '#F97316',
    description: 'Forearms on floor with your body in a straight line from head to heels. Squeeze glutes and brace your abs. Breathe steadily throughout.',
  },
  {
    id: 'core-2',
    name: 'Crunch',
    muscleGroup: 'core',
    sets: 3,
    reps: 20,
    difficulty: 'beginner',
    color: '#F97316',
    description: 'Hands behind head with feet flat on the floor. Curl your shoulders up and exhale at the top. Lower slowly. Focus on abs not your neck.',
  },
  {
    id: 'core-3',
    name: 'Mountain Climber',
    muscleGroup: 'core',
    sets: 3,
    reps: 20,
    difficulty: 'beginner',
    color: '#F97316',
    description: 'Start in a high plank position. Drive your knees alternately toward your chest at pace. Keep your hips level and core tight throughout.',
  },
  {
    id: 'core-4',
    name: 'Dead Bug',
    muscleGroup: 'core',
    sets: 3,
    reps: 10,
    difficulty: 'beginner',
    color: '#F97316',
    description: 'Lie on your back with arms and knees raised to 90°. Lower opposite arm and leg slowly toward the floor. Keep your lower back pressed down.',
  },
  {
    id: 'core-5',
    name: 'Bicycle Crunch',
    muscleGroup: 'core',
    sets: 3,
    reps: 20,
    difficulty: 'intermediate',
    color: '#F97316',
    description: 'Hands behind head with legs lifted. Bring your elbow toward your opposite knee as you extend the other leg. Slow and deliberate rotation.',
  },
  {
    id: 'core-6',
    name: 'Hanging Leg Raise',
    muscleGroup: 'core',
    sets: 3,
    reps: 12,
    difficulty: 'intermediate',
    color: '#F97316',
    description: 'Hang from a pull-up bar with legs together. Raise your legs to 90° without swinging. Lower with full control. Avoid momentum.',
  },
  {
    id: 'core-7',
    name: 'Ab Wheel Rollout',
    muscleGroup: 'core',
    sets: 3,
    reps: 10,
    difficulty: 'advanced',
    color: '#F97316',
    description: 'Kneel with the wheel in front of you. Roll forward until your hips are fully extended, bracing hard. Pull back using your abs, not your back.',
  },
  {
    id: 'core-8',
    name: 'Russian Twist',
    muscleGroup: 'core',
    sets: 3,
    reps: 20,
    difficulty: 'intermediate',
    color: '#F97316',
    description: 'Seated with legs raised and feet together. Rotate your torso side to side touching the floor on each side. Add a weight plate to progress.',
  },
]

export const MUSCLE_GROUP_LABELS: Record<MuscleGroup, string> = {
  back: 'Back',
  chest: 'Chest',
  arms: 'Arms',
  legs: 'Legs',
  shoulders: 'Shoulders',
  core: 'Core',
}

export const MUSCLE_GROUP_ICONS: Record<MuscleGroup, string> = {
  back: '🏋️',
  chest: '💪',
  arms: '🦾',
  legs: '🦵',
  shoulders: '🔱',
  core: '🎯',
}
